version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: turf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - turf_network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  redis:
    image: redis:alpine
    container_name: turf_redis
    ports:
      - "6380:6379"
    networks:
      - turf_network

  api-gateway:
    build:
      context: ../Turf-Booking-Platform-Backend/api-gateway
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-api-gateway:latest
    container_name: turf_api_gateway
    ports:
      - "5004:5000"
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth-service:5001
      - TURF_SERVICE_URL=http://turf-service:5002
      - BOOKING_SERVICE_URL=http://booking-service:5003
      - REDIS_URL=redis://redis:6379
    depends_on:
      - auth-service
      - turf-service
      - booking-service
      - redis
    networks:
      - turf_network

  auth-service:
    build:
      context: ../Turf-Booking-Platform-Backend/auth-service
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-auth-service:latest
    container_name: turf_auth_service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/turf_booking
      - PORT=5001
      - CLIENT_URL=http://localhost
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - turf_network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  turf-service:
    build:
      context: ../Turf-Booking-Platform-Backend/turf-service
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-turf-service:latest
    container_name: turf_turf_service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/turf_booking
      - PORT=5002
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - turf_network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  booking-service:
    build:
      context: ../Turf-Booking-Platform-Backend/booking-service
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-booking-service:latest
    container_name: turf_booking_service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/turf_booking
      - PORT=5003
      - REDIS_URI=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - turf_network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  frontend:
    build:
      context: ../Turf-Booking-Platform-Frontend
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-frontend:latest
    container_name: turf_frontend
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - turf_network

volumes:
  mongodb_data:

networks:
  turf_network:
    driver: bridge
