apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turf-platform

resources:
  - namespace.yaml
  - mongodb.yaml
  - redis.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - turf-service.yaml
  - booking-service.yaml
  - frontend.yaml
