apiVersion: apps/v1
kind: Deployment
metadata:
  name: turf-service
  namespace: turf-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turf-service
  template:
    metadata:
      labels:
        app: turf-service
    spec:
      containers:
      - name: turf-service
        image: prateekkumaryadav/turf-turf-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/turf_booking"
---
apiVersion: v1
kind: Service
metadata:
  name: turf-service
  namespace: turf-platform
spec:
  selector:
    app: turf-service
  ports:
  - port: 5002
    targetPort: 5002
