input {
  gelf {
    port => 12201
  }
}

filter {
  json {
    source => "message"
    target => "app"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "turf-platform-%{+YYYY.MM.dd}"
  }
}
